### ISSUE TITLE
TA Comment - 撰寫使用者需求以及需求規格書

### ISSUE THREAD

**Issue by jo-ym** [D0543027/BaseProject#2]
1. 開發同意書至少寫上雙方組名。
2. "想多認識女生，列出女生較多的課堂，供參考"此項功能, 在規格中的描述看起來只是查詢課程選課的學生, 並沒有過濾過"女生較多"這點。

**Comment by shchiang0708** [comment]
20171114 已更正

**Comment by jo-ym** [comment]
已修改分數
